### PR TITLE
Added support for extra setting screen

### PR DESCRIPTION
**Pull request by Aazamandius**

### CODE REVIEW

**Comment by Aazamandius** [comment]
It works (in debug mode with Qt creator under windows) right but there are problems with libraries - after the intro screen is shown (fei base) there are some errors in the console (like can't parse JSON file) - I think I can't assemble it the right way

**Comment by mdimura** [comment]
I've released the new version with this change, please test if it works for you.

**Comment by Aazamandius** [comment]
Thank you ))),
I've found how to build it in Docker - everything works well  (in old and new ways both)
I'm already generating galaxies

**Comment by mdimura** [comment]
You can find the build script (win/linux) for docker in the `.gitlab-ci.yml` file if you need it.

**Comment by Aazamandius** [comment]
Yes, I found it - but I've never worked with docker before. 
Then I copied the project to git gitlab (i know about their CI, set up my own build machine) an just pressed "run pipeline"
Then it built everything for me ) (as I understand later it has their own machines for docker build configs)

**Pull request merged**
